[platformio]
default_envs = giga_m7, giga_m4

[env]
platform = ststm32
framework = arduino
build_flags =
    -Iinclude
lib_deps = 
    pololu/Motoron @ ^1.3.0
    arduino-libraries/Servo @ ^1.2.1
    arduino-libraries/ArduinoMqttClient


[env:giga_m7]
board = giga_r1_m7
build_flags = 
    ${env.build_flags}
    -D CORE_CM7
    -Wl,--allow-multiple-definition
monitor_speed = 115200


[env:giga_m4]
board = giga_r1_m4
build_flags =
    ${env.build_flags}
    -D CORE_CM4
monitor_speed = 115200
