[platformio]
default_envs = giga_m7

[env]
platform = ststm32
framework = arduino
lib_deps = 
    pololu/Motoron @ ^1.3.0
    arduino-libraries/Servo @ ^1.2.1
    arduino-libraries/ArduinoMqttClient


[env:giga_m7]
board = giga_r1_m7
build_flags = 
    -D CORE_CM7
    -Iinclude
    -Wl,--allow-multiple-definition
monitor_speed = 115200


[env:giga_m4]
board = giga_r1_m4
build_flags = -D CORE_CM4
monitor_speed = 115200

[env:kill_switch_test]
board = giga_r1_m7
build_flags = 
    -D CORE_CM7
    -Iinclude
build_src_filter = 
    -<*>
    +<../test/kill_switch.cpp>
monitor_speed = 115200

[env:safety_buttons_test]
board = giga_r1_m7
build_flags =
    -D CORE_CM7
    -Iinclude
build_src_filter =
    -<*>
    +<../test/safety_buttons.cpp>
monitor_speed = 115200

