#pragma once

#define MOTORON_ADDR_FRONT 0x60
#define MOTORON_ADDR_REAR  0x10

#define MOTOR_FL 1
#define MOTOR_FR 2
#define MOTOR_RL 1
#define MOTOR_RR 2

#define MOTOR_MAX_SPEED 800

#define MOTORON_MAX_ACCELERATION 200
#define MOTORON_MAX_DECELERATION 200
